name = "Yarn Spinner"
grammar = "yarn_spinner"
path_suffixes = ["yarn"]
line_comments = ["// "]
tab_size = 4
hard_tabs = false
word_characters = ["$", "#", "_"]

# Auto-closing bracket pairs
brackets = [
  { start = "(", end = ")", close = true, newline = false },
  { start = "[", end = "]", close = true, newline = false },
  { start = "{", end = "}", close = true, newline = false },
  { start = "\"", end = "\"", close = true, newline = false },
  { start = "<", end = ">", close = false, newline = false }, # avoid auto-close to not conflict with << >>
]

# Disable auto-closing single quote in strings (Yarn uses double quotes primarily)
# and ensure $ and # behave as word characters everywhere.
[overrides.string]
completion_query_characters = ["-"]
